/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mostafa
 */
public class Admin_dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(Admin_dashboard.class.getName());
    
    // ✅ 1 - الـ Constructor
    public Admin_dashboard() {
        initComponents();
        loadHomeStats();
        loadStudents();
        loadCourses();
        loadEnrollments();
    }

    // ✅ 2 - الدوال هنا بعد الـ Constructor مباشرة
    private void loadHomeStats() {
        try {
            java.sql.ResultSet rs1 = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT COUNT(*) FROM students");
            if (rs1.next()) lblStudentCount.setText(String.valueOf(rs1.getInt(1)));

            java.sql.ResultSet rs2 = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT COUNT(*) FROM courses");
            if (rs2.next()) lblCourseCount.setText(String.valueOf(rs2.getInt(1)));

            java.sql.ResultSet rs3 = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT COUNT(*) FROM enrollments");
            if (rs3.next()) lblEnrollCount.setText(String.valueOf(rs3.getInt(1)));

        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }

    private void loadStudents() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);
        try {
            java.sql.ResultSet rs = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT * FROM students");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("full_name"),
                    rs.getString("email"),
                    rs.getString("phone"),
                    rs.getTimestamp("created_at")
                });
            }
        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }

    private void loadCourses() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);
        try {
            java.sql.ResultSet rs = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT * FROM courses");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getString("description"),
                    rs.getString("instructor")
                });
            }
        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }

    private void loadEnrollments() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblEnrol

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnRefreshStudents = new javax.swing.JButton();
        textSearchCourse = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAddCourse = new javax.swing.JButton();
        btnEditCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnRefreshCourses = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        textSearchCourse1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnDeleteEnrollment = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnRefreshEnrollments = new javax.swing.JButton();
        btnSearch2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        textSearchCourse2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnCount = new javax.swing.JButton();
        btnMax = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnPopular = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnAddAdmin = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome Admin");

        jPanel8.setBackground(new java.awt.Color(51, 255, 255));

        jLabel2.setText("Total Students");

        jLabel5.setText("num of student");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setText("Total Courses");

        jLabel6.setText("num of cources ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel6)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setText("Total Enrollments");

        jLabel7.setText("num of enrollment");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(this::btnAddStudentActionPerformed);

        btnEditStudent.setText("Edit");
        btnEditStudent.addActionListener(this::btnEditStudentActionPerformed);

        btnDeleteStudent.setText("Delete");
        btnDeleteStudent.addActionListener(this::btnDeleteStudentActionPerformed);

        btnRefreshStudents.setText("Refresh Data");
        btnRefreshStudents.addActionListener(this::btnRefreshStudentsActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        jLabel8.setText("Search :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name ", "Email ", "Phone", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane4.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAddStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnRefreshStudents))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnAddStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefreshStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Students", jPanel2);

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(this::btnAddCourseActionPerformed);

        btnEditCourse.setText("Edit");
        btnEditCourse.addActionListener(this::btnEditCourseActionPerformed);

        btnDeleteCourse.setText("Delete");
        btnDeleteCourse.addActionListener(this::btnDeleteCourseActionPerformed);

        btnRefreshCourses.setText("Refresh");
        btnRefreshCourses.addActionListener(this::btnRefreshCoursesActionPerformed);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cource_ID", "Cource_Name", "Cource_instructor", "Cource_Duration"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jScrollPane5.setViewportView(jScrollPane2);

        btnSearch1.setText("Search");
        btnSearch1.addActionListener(this::btnSearch1ActionPerformed);

        jLabel9.setText("Search :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnEditCourse)
                                .addGap(55, 55, 55)
                                .addComponent(btnDeleteCourse)
                                .addGap(47, 47, 47)
                                .addComponent(btnRefreshCourses))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSearchCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch1)))
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textSearchCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch1))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourse)
                    .addComponent(btnEditCourse)
                    .addComponent(btnDeleteCourse)
                    .addComponent(btnRefreshCourses))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Courses", jPanel3);

        btnDeleteEnrollment.setText("Delete ");
        btnDeleteEnrollment.addActionListener(this::btnDeleteEnrollmentActionPerformed);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Student Name", "Course Name", "Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jScrollPane6.setViewportView(jScrollPane3);

        btnRefreshEnrollments.setText("Refresh ");
        btnRefreshEnrollments.addActionListener(this::btnRefreshEnrollmentsActionPerformed);

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(this::btnSearch2ActionPerformed);

        jLabel10.setText("Search :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSearchCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnDeleteEnrollment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshEnrollments)
                .addGap(171, 171, 171))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textSearchCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEnrollment)
                    .addComponent(btnRefreshEnrollments))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Enrollments", jPanel4);

        btnCount.setText("Count");
        btnCount.addActionListener(this::btnCountActionPerformed);

        btnMax.setText("Max");
        btnMax.addActionListener(this::btnMaxActionPerformed);

        btnMin.setText("Min");
        btnMin.addActionListener(this::btnMinActionPerformed);

        jLabel11.setText(" Statistics & Reports");

        btnPopular.setText("Most Popular Course ");
        btnPopular.addActionListener(this::btnPopularActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnCount)
                        .addGap(63, 63, 63)
                        .addComponent(btnMax)
                        .addGap(48, 48, 48)
                        .addComponent(btnMin))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnPopular))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCount)
                    .addComponent(btnMax)
                    .addComponent(btnMin))
                .addGap(46, 46, 46)
                .addComponent(btnPopular)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reports", jPanel5);

        jLabel13.setText("User name :");

        txtUsername.setText("jTextField1");

        jLabel14.setText("Password :");

        txtPassword.setText("jPasswordField1");
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        btnAddAdmin.setText("Add Admin");
        btnAddAdmin.addActionListener(this::btnAddAdminActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddAdmin)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(btnAddAdmin)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admins", jPanel6);

        jLabel12.setText("Are you sure you want to logout?");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(184, 184, 184))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel12)
                .addGap(83, 83, 83)
                .addComponent(btnLogout)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Logout", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
private void btnFilterEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {
    String keyword = txtSearchEnrollment.getText().trim();
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblEnrollments.getModel();
    model.setRowCount(0);
    try {
        java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
            "SELECT e.id, s.full_name, c.name, e.enrolled_at " +
            "FROM enrollments e " +
            "JOIN students s ON e.student_id=s.id " +
            "JOIN courses c ON e.course_id=c.id " +
            "WHERE s.full_name LIKE ? OR c.name LIKE ? " +
            "ORDER BY e.enrolled_at DESC"
        );
        stmt.setString(1, "%" + keyword + "%");
        stmt.setString(2, "%" + keyword + "%");
        java.sql.ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("full_name"),
                rs.getString("name"),
                rs.getTimestamp("enrolled_at")
            });
        }
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
private void btnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {
    String keyword = txtSearchStudent.getText().trim();
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblStudents.getModel();
    model.setRowCount(0);
    try {
        java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
            "SELECT * FROM students WHERE full_name LIKE ? OR email LIKE ?"
        );
        stmt.setString(1, "%" + keyword + "%");
        stmt.setString(2, "%" + keyword + "%");
        java.sql.ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("full_name"),
                rs.getString("email"),
                rs.getString("phone"),
                rs.getTimestamp("created_at")
            });
        }
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {
    int row = tblStudents.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a student first!");
        return;
    }

    int id = (int) tblStudents.getValueAt(row, 0);

    JTextField fName  = new JTextField((String) tblStudents.getValueAt(row, 1));
    JTextField fEmail = new JTextField((String) tblStudents.getValueAt(row, 2));
    JTextField fPhone = new JTextField((String) tblStudents.getValueAt(row, 3));

    Object[] fields = {
        "Full Name:", fName,
        "Email:",     fEmail,
        "Phone:",     fPhone
    };

    int result = JOptionPane.showConfirmDialog(this, fields, "Edit Student", JOptionPane.OK_CANCEL_OPTION);

    if (result == JOptionPane.OK_OPTION) {
        try {
            java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                "UPDATE students SET full_name=?, email=?, phone=? WHERE id=?"
            );
            stmt.setString(1, fName.getText());
            stmt.setString(2, fEmail.getText());
            stmt.setString(3, fPhone.getText());
            stmt.setInt(4, id);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Student updated successfully!");
            loadStudents();

        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {
    JTextField fName  = new JTextField();
    JTextField fEmail = new JTextField();
    JTextField fPhone = new JTextField();
    JPasswordField fPass = new JPasswordField();

    Object[] fields = {
        "Full Name:", fName,
        "Email:",     fEmail,
        "Phone:",     fPhone,
        "Password:",  fPass
    };

    int result = JOptionPane.showConfirmDialog(this, fields, "Add New Student", JOptionPane.OK_CANCEL_OPTION);

    if (result == JOptionPane.OK_OPTION) {
        try {
            java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                "INSERT INTO students (full_name, email, password, phone) VALUES (?,?,?,?)"
            );
            stmt.setString(1, fName.getText());
            stmt.setString(2, fEmail.getText());
            stmt.setString(3, hashMD5(new String(fPass.getPassword())));
            stmt.setString(4, fPhone.getText());
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Student added successfully!");
            loadStudents();
            loadHomeStats();

        } catch (java.sql.SQLException e) {
            if (e.getMessage().contains("Duplicate")) {
                JOptionPane.showMessageDialog(this, "Email already exists!");
            } else {
                e.printStackTrace();
            }
        }
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {
    int row = tblStudents.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a student first!");
        return;
    }

    int id   = (int) tblStudents.getValueAt(row, 0);
    String name = (String) tblStudents.getValueAt(row, 1);

    int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete " + name + "?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            db.DBConnection.getConnection().createStatement()
                .executeUpdate("DELETE FROM students WHERE id=" + id);

            JOptionPane.showMessageDialog(this, "Student deleted successfully!");
            loadStudents();
            loadHomeStats();

        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnRefreshStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshStudentsActionPerformed
private void btnRefreshStudentsActionPerformed(java.awt.event.ActionEvent evt) {
    loadStudents();
    JOptionPane.showMessageDialog(this, "Data refreshed!");
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshStudentsActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {
    JTextField fName       = new JTextField();
    JTextField fDesc       = new JTextField();
    JTextField fInstructor = new JTextField();

    Object[] fields = {
        "Course Name:",  fName,
        "Description:",  fDesc,
        "Instructor:",   fInstructor
    };

    int result = JOptionPane.showConfirmDialog(this, fields, "Add New Course", JOptionPane.OK_CANCEL_OPTION);

    if (result == JOptionPane.OK_OPTION) {
        try {
            java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                "INSERT INTO courses (name, description, instructor) VALUES (?,?,?)"
            );
            stmt.setString(1, fName.getText());
            stmt.setString(2, fDesc.getText());
            stmt.setString(3, fInstructor.getText());
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Course added successfully!");
            loadCourses();
            loadHomeStats();

        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {
    int row = tblCourses.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first!");
        return;
    }

    int id = (int) tblCourses.getValueAt(row, 0);
    String name = (String) tblCourses.getValueAt(row, 1);

    int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete " + name + "?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            db.DBConnection.getConnection().createStatement()
                .executeUpdate("DELETE FROM courses WHERE id=" + id);

            JOptionPane.showMessageDialog(this, "Course deleted successfully!");
            loadCourses();
            loadHomeStats();

        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnRefreshCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCoursesActionPerformed
private void btnRefreshCoursesActionPerformed(java.awt.event.ActionEvent evt) {
    loadCourses();
    JOptionPane.showMessageDialog(this, "Courses refreshed!");
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshCoursesActionPerformed

    private void btnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCourseActionPerformed
private void btnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {
    
    // تأكد إن المستخدم اختار row من الجدول
    int row = tblCourses.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first!");
        return;
    }

    // جيب البيانات من الـ row المختار
    int id             = (int)    tblCourses.getValueAt(row, 0);
    String currentName = (String) tblCourses.getValueAt(row, 1);
    String currentDesc = (String) tblCourses.getValueAt(row, 2);
    String currentInst = (String) tblCourses.getValueAt(row, 3);

    // اعمل fields جاهزة فيها البيانات القديمة
    JTextField fName       = new JTextField(currentName);
    JTextField fDesc       = new JTextField(currentDesc);
    JTextField fInstructor = new JTextField(currentInst);

    Object[] fields = {
        "Course Name:",  fName,
        "Description:",  fDesc,
        "Instructor:",   fInstructor
    };

    // اعرض الـ dialog للتعديل
    int result = JOptionPane.showConfirmDialog(
        this, fields, "Edit Course", JOptionPane.OK_CANCEL_OPTION
    );

    if (result == JOptionPane.OK_OPTION) {
        
        // تأكد إن الاسم مش فاضي
        if (fName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Course name cannot be empty!");
            return;
        }

        try {
            java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                "UPDATE courses SET name=?, description=?, instructor=? WHERE id=?"
            );
            stmt.setString(1, fName.getText().trim());
            stmt.setString(2, fDesc.getText().trim());
            stmt.setString(3, fInstructor.getText().trim());
            stmt.setInt(4, id);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Course updated successfully!");
            
            // تحديث الجدول
            loadCourses();

        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error updating course!");
        }
    }
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnEditCourseActionPerformed

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountActionPerformed
private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        java.sql.ResultSet rs = db.DBConnection.getConnection()
            .createStatement().executeQuery("SELECT COUNT(*) FROM students");
        if (rs.next())
            txtResult.setText("Total Students: " + rs.getInt(1));
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnCountActionPerformed

    private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxActionPerformed
private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        java.sql.ResultSet rs = db.DBConnection.getConnection()
            .createStatement().executeQuery("SELECT MAX(id) FROM students");
        if (rs.next())
            txtResult.setText("Max Student ID: " + rs.getInt(1));
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
}
    // TODO add your handling code here:
    }//GEN-LAST:event_btnMaxActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        java.sql.ResultSet rs = db.DBConnection.getConnection()
            .createStatement().executeQuery("SELECT MIN(id) FROM students");
        if (rs.next())
            txtResult.setText("Min Student ID: " + rs.getInt(1));
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
}
    // TODO add your handling code here:
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopularActionPerformed
private void btnPopularActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        java.sql.ResultSet rs = db.DBConnection.getConnection().createStatement().executeQuery(
            "SELECT c.name, COUNT(*) as cnt FROM enrollments e " +
            "JOIN courses c ON e.course_id=c.id " +
            "GROUP BY e.course_id ORDER BY cnt DESC LIMIT 1"
        );
        if (rs.next())
            txtResult.setText("Most Popular Course: " + rs.getString("name") +
                " (" + rs.getInt("cnt") + " students)");
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
}
    // TODO add your handling code here:
    }//GEN-LAST:event_btnPopularActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
private void btnAdminLogoutActionPerformed(java.awt.event.ActionEvent evt) {
    int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose();
    }
}
    // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshEnrollmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshEnrollmentsActionPerformed
private void btnRefreshEnrollmentsActionPerformed(java.awt.event.ActionEvent evt) {
    loadEnrollments();
    JOptionPane.showMessageDialog(this, "Enrollments refreshed!");
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshEnrollmentsActionPerformed

    private void btnDeleteEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEnrollmentActionPerformed
private void btnDeleteEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {
    int row = tblEnrollments.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select an enrollment first!");
        return;
    }

    int id          = (int)    tblEnrollments.getValueAt(row, 0);
    String student  = (String) tblEnrollments.getValueAt(row, 1);
    String course   = (String) tblEnrollments.getValueAt(row, 2);

    int confirm = JOptionPane.showConfirmDialog(this,
        "Delete enrollment of " + student + " from " + course + "?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                "DELETE FROM enrollments WHERE id=?"
            );
            stmt.setInt(1, id);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Enrollment deleted successfully!");
            loadEnrollments();
            loadHomeStats(); // تحديث العداد في الهوم

        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error deleting enrollment!");
        }
    }
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteEnrollmentActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
String username = txtUsername.getText();
String password = new String(txtPassword.getPassword());

// Validation
if (username.isEmpty() || password.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please fill all fields");
    return;
}

// Hash password باستخدام MD5
String hashedPassword = hashMD5(password);

try {
    Connection con = DBConnection.connect();

    String query = "INSERT INTO admins (username, password) VALUES (?, ?)";
    PreparedStatement ps = con.prepareStatement(query);

    ps.setString(1, username);
    ps.setString(2, hashedPassword);

    ps.executeUpdate();

    JOptionPane.showMessageDialog(null, "Admin added successfully");

    // تنظيف الحقول
    txtUsername.setText("");
    txtPassword.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_dashboard().setVisible(true));
        private String hashMD5(String input) {
    try {
        java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
        byte[] hash = md.digest(input.getBytes("UTF-8"));
        StringBuilder sb = new StringBuilder();
        for (byte b : hash) sb.append(String.format("%02x", b));
        return sb.toString();
    } catch (Exception e) {
        return input;
    }
}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnDeleteEnrollment;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnEditCourse;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMax;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnPopular;
    private javax.swing.JButton btnRefreshCourses;
    private javax.swing.JButton btnRefreshEnrollments;
    private javax.swing.JButton btnRefreshStudents;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textSearchCourse;
    private javax.swing.JTextField textSearchCourse1;
    private javax.swing.JTextField textSearchCourse2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

