/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mostafa
 */
import javax.swing.*;
import java.sql.*;
public class Admin_dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(Admin_dashboard.class.getName());
    
    // ✅ 1 - الـ Constructor
    public Admin_dashboard() {
        initComponents();
        loadHomeStats();
        loadStudents();
        loadCourses();
        loadEnrollments();
    }

    // ✅ 2 - الدوال هنا بعد الـ Constructor مباشرة
    private void loadHomeStats() {
        try {
            java.sql.ResultSet rs1 = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT COUNT(*) FROM students");
            if (rs1.next()) lblStudentCount.setText(String.valueOf(rs1.getInt(1)));

            java.sql.ResultSet rs2 = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT COUNT(*) FROM courses");
            if (rs2.next()) lblCourseCount.setText(String.valueOf(rs2.getInt(1)));

            java.sql.ResultSet rs3 = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT COUNT(*) FROM enrollments");
            if (rs3.next()) lblEnrollCount.setText(String.valueOf(rs3.getInt(1)));

        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }

        private void loadStudents() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);
        try {
            java.sql.ResultSet rs = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT * FROM students");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("first_name") + " " + rs.getString("last_name"),
                    rs.getString("email"),
                    rs.getString("phone"),
                    rs.getTimestamp("created_at")
                });
            }
        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }

        private void loadCourses() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);
        try {
            java.sql.ResultSet rs = db.DBConnection.getConnection()
                .createStatement().executeQuery("SELECT * FROM courses");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"), rs.getString("name"),
                    rs.getString("instructor"), rs.getString("duration")
                });
            }
        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }

    private void loadEnrollments() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblEnrollments.getModel();
    model.setRowCount(0);
    try {
        java.sql.ResultSet rs = db.DBConnection.getConnection().createStatement().executeQuery(
            "SELECT e.id, CONCAT(s.first_name,' ',s.last_name), c.name, e.enrolled_at " +
            "FROM enrollments e " +
            "JOIN students s ON e.student_id=s.id " +
            "JOIN courses c ON e.course_id=c.id ORDER BY e.enrolled_at DESC"
        );
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt(1), rs.getString(2), rs.getString(3), rs.getTimestamp(4)
            });
        }
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblStudentCount = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCourseCount = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblEnrollCount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnRefreshStudents = new javax.swing.JButton();
        txtSearchStudent = new javax.swing.JTextField();
        btnSearchStudent = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAddCourse = new javax.swing.JButton();
        btnEditCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnRefreshCourses = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        txtSearchCourse = new javax.swing.JTextField();
        btnSearchCourse = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnDeleteEnrollment = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEnrollments = new javax.swing.JTable();
        btnRefreshEnrollments = new javax.swing.JButton();
        btnSearchEnrollment = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSearchEnrollment = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnCount = new javax.swing.JButton();
        btnMax = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnPopular = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAdminPassword = new javax.swing.JPasswordField();
        btnAddAdmin = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnAdminLogout = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome Admin");

        jPanel8.setBackground(new java.awt.Color(51, 255, 255));

        jLabel2.setText("Total Students");

        lblStudentCount.setText("num of student");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblStudentCount)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(lblStudentCount)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setText("Total Courses");

        lblCourseCount.setText("num of cources ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(lblCourseCount, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(lblCourseCount)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setText("Total Enrollments");

        lblEnrollCount.setText("num of enrollment");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEnrollCount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblEnrollCount)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(this::btnAddStudentActionPerformed);

        btnEditStudent.setText("Edit");
        btnEditStudent.addActionListener(this::btnEditStudentActionPerformed);

        btnDeleteStudent.setText("Delete");
        btnDeleteStudent.addActionListener(this::btnDeleteStudentActionPerformed);

        btnRefreshStudents.setText("Refresh Data");
        btnRefreshStudents.addActionListener(this::btnRefreshStudentsActionPerformed);

        btnSearchStudent.setText("Search");
        btnSearchStudent.addActionListener(this::btnSearchStudentActionPerformed);

        jLabel8.setText("Search :");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name ", "Email ", "Phone", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        jScrollPane4.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAddStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnRefreshStudents))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchStudent)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStudent))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnAddStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefreshStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Students", jPanel2);

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(this::btnAddCourseActionPerformed);

        btnEditCourse.setText("Edit");
        btnEditCourse.addActionListener(this::btnEditCourseActionPerformed);

        btnDeleteCourse.setText("Delete");
        btnDeleteCourse.addActionListener(this::btnDeleteCourseActionPerformed);

        btnRefreshCourses.setText("Refresh");
        btnRefreshCourses.addActionListener(this::btnRefreshCoursesActionPerformed);

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cource_ID", "Cource_Name", "Cource_instructor", "Cource_Duration"
            }
        ));
        jScrollPane2.setViewportView(tblCourses);

        jScrollPane5.setViewportView(jScrollPane2);

        btnSearchCourse.setText("Search");
        btnSearchCourse.addActionListener(this::btnSearchCourseActionPerformed);

        jLabel9.setText("Search :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnEditCourse)
                                .addGap(55, 55, 55)
                                .addComponent(btnDeleteCourse)
                                .addGap(47, 47, 47)
                                .addComponent(btnRefreshCourses))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchCourse)))
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCourse))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourse)
                    .addComponent(btnEditCourse)
                    .addComponent(btnDeleteCourse)
                    .addComponent(btnRefreshCourses))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Courses", jPanel3);

        btnDeleteEnrollment.setText("Delete ");
        btnDeleteEnrollment.addActionListener(this::btnDeleteEnrollmentActionPerformed);

        tblEnrollments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Student Name", "Course Name", "Date"
            }
        ));
        jScrollPane3.setViewportView(tblEnrollments);

        jScrollPane6.setViewportView(jScrollPane3);

        btnRefreshEnrollments.setText("Refresh ");
        btnRefreshEnrollments.addActionListener(this::btnRefreshEnrollmentsActionPerformed);

        btnSearchEnrollment.setText("Search");
        btnSearchEnrollment.addActionListener(this::btnSearchEnrollmentActionPerformed);

        jLabel10.setText("Search :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchEnrollment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnDeleteEnrollment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshEnrollments)
                .addGap(171, 171, 171))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSearchEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchEnrollment))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEnrollment)
                    .addComponent(btnRefreshEnrollments))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Enrollments", jPanel4);

        btnCount.setText("Count");
        btnCount.addActionListener(this::btnCountActionPerformed);

        btnMax.setText("Max");
        btnMax.addActionListener(this::btnMaxActionPerformed);

        btnMin.setText("Min");
        btnMin.addActionListener(this::btnMinActionPerformed);

        jLabel11.setText(" Statistics & Reports");

        btnPopular.setText("Most Popular Course ");
        btnPopular.addActionListener(this::btnPopularActionPerformed);

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane7.setViewportView(txtResult);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnCount)
                        .addGap(63, 63, 63)
                        .addComponent(btnMax)
                        .addGap(48, 48, 48)
                        .addComponent(btnMin))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnPopular))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCount)
                    .addComponent(btnMax)
                    .addComponent(btnMin))
                .addGap(46, 46, 46)
                .addComponent(btnPopular)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reports", jPanel5);

        jLabel13.setText("User name :");

        txtAdminUsername.setText("jTextField1");

        jLabel14.setText("Password :");

        txtAdminPassword.setText("jPasswordField1");
        txtAdminPassword.addActionListener(this::txtAdminPasswordActionPerformed);

        btnAddAdmin.setText("Add Admin");
        btnAddAdmin.addActionListener(this::btnAddAdminActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddAdmin)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminUsername)
                            .addComponent(txtAdminPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(btnAddAdmin)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admins", jPanel6);

        jLabel12.setText("Are you sure you want to logout?");

        btnAdminLogout.setText("Logout");
        btnAdminLogout.addActionListener(this::btnAdminLogoutActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAdminLogout)
                        .addGap(184, 184, 184))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel12)
                .addGap(83, 83, 83)
                .addComponent(btnAdminLogout)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Logout", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEnrollmentActionPerformed
 // TODO add your handling code here:
        String keyword = txtSearchEnrollment.getText().trim();
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblEnrollments.getModel();
    model.setRowCount(0);
    try {
        java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
            "SELECT e.id, CONCAT(s.first_name,' ',s.last_name), c.name, e.enrolled_at " +
            "FROM enrollments e JOIN students s ON e.student_id=s.id " +
            "JOIN courses c ON e.course_id=c.id " +
            "WHERE s.first_name LIKE ? OR s.last_name LIKE ? OR c.name LIKE ?"
        );
        stmt.setString(1,"%"+keyword+"%"); stmt.setString(2,"%"+keyword+"%"); stmt.setString(3,"%"+keyword+"%");
        java.sql.ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getTimestamp(4)});
        }
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnSearchEnrollmentActionPerformed

    private void btnSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCourseActionPerformed
        // TODO add your handling code here:
            String keyword = txtSearchCourse.getText().trim();
            javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) tblCourses.getModel();
            model.setRowCount(0);
            try {
                java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                    "SELECT * FROM courses WHERE name LIKE ? OR instructor LIKE ?"
                );
                stmt.setString(1, "%"+keyword+"%"); stmt.setString(2, "%"+keyword+"%");
                java.sql.ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id"), rs.getString("name"),
                        rs.getString("instructor"), rs.getString("duration")
                    });
                }
            } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnSearchCourseActionPerformed

    private void btnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentActionPerformed
        // TODO add your handling code here:
        String keyword = txtSearchStudent.getText().trim();
            javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) tblStudents.getModel();
            model.setRowCount(0);
            try {
                java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                    "SELECT * FROM students WHERE first_name LIKE ? OR last_name LIKE ? OR email LIKE ?"
                );
                stmt.setString(1, "%"+keyword+"%"); stmt.setString(2, "%"+keyword+"%"); stmt.setString(3, "%"+keyword+"%");
                java.sql.ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("first_name") + " " + rs.getString("last_name"),
                        rs.getString("email"), rs.getString("phone"), rs.getTimestamp("created_at")
                    });
                }
            } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnSearchStudentActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
        // TODO add your handling code here
        int row = tblStudents.getSelectedRow();
        if (row == -1) { JOptionPane.showMessageDialog(this, "Please select a student first!"); return; }
        int id = (int) tblStudents.getValueAt(row, 0);
        JTextField fEmail = new JTextField((String) tblStudents.getValueAt(row, 2));
        JTextField fPhone = new JTextField((String) tblStudents.getValueAt(row, 3));
        Object[] fields = {"Email:", fEmail, "Phone:", fPhone};
        int result = JOptionPane.showConfirmDialog(this, fields, "Edit Student", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            try {
                java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                    "UPDATE students SET email=?, phone=? WHERE id=?"
                );
                stmt.setString(1, fEmail.getText()); stmt.setString(2, fPhone.getText()); stmt.setInt(3, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Student updated successfully!");
                loadStudents();
            } catch (java.sql.SQLException e) { e.printStackTrace(); }
        }
    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // TODO add your handling code here:
            JTextField fFirst = new JTextField(); JTextField fLast = new JTextField();
            JTextField fEmail = new JTextField(); JTextField fPhone = new JTextField();
            JTextField fUser  = new JTextField(); JPasswordField fPass = new JPasswordField();

            Object[] fields = {
                "First Name:", fFirst, "Last Name:", fLast,
                "Email:", fEmail, "Phone:", fPhone,
                "Username:", fUser, "Password:", fPass
            };
            int result = JOptionPane.showConfirmDialog(this, fields, "Add New Student", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                try {
                    java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                        "INSERT INTO students (first_name, last_name, email, phone, username, password) VALUES (?,?,?,?,?,?)"
                    );
                    stmt.setString(1, fFirst.getText()); stmt.setString(2, fLast.getText());
                    stmt.setString(3, fEmail.getText()); stmt.setString(4, fPhone.getText());
                    stmt.setString(5, fUser.getText());
                    stmt.setString(6, hashMD5(new String(fPass.getPassword())));
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Student added successfully!");
                    loadStudents(); loadHomeStats();
                } catch (java.sql.SQLException e) {
                    if (e.getMessage().contains("Duplicate"))
                        JOptionPane.showMessageDialog(this, "Email or Username already exists!");
                    else e.printStackTrace();
                }
            }
            
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnRefreshStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshStudentsActionPerformed
        // TODO add your handling code here:
    loadStudents();
        
    }//GEN-LAST:event_btnRefreshStudentsActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        JTextField fName = new JTextField(); JTextField fDesc = new JTextField();
        JTextField fInst = new JTextField(); JTextField fDur  = new JTextField();
        Object[] fields = {"Course Name:", fName, "Description:", fDesc, "Instructor:", fInst, "Duration:", fDur};
        int result = JOptionPane.showConfirmDialog(this, fields, "Add Course", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            try {
                java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                    "INSERT INTO courses (name, description, instructor, duration) VALUES (?,?,?,?)"
                );
                stmt.setString(1, fName.getText()); stmt.setString(2, fDesc.getText());
                stmt.setString(3, fInst.getText()); stmt.setString(4, fDur.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Course added successfully!");
                loadCourses(); loadHomeStats();
            } catch (java.sql.SQLException e) { e.printStackTrace(); }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
// TODO add your handling code here:
        int row = tblCourses.getSelectedRow();
        if (row == -1) { JOptionPane.showMessageDialog(this, "Please select a course first!"); return; }
        int id = (int) tblCourses.getValueAt(row, 0);
        String name = (String) tblCourses.getValueAt(row, 1);
        int confirm = JOptionPane.showConfirmDialog(this, "Delete " + name + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                db.DBConnection.getConnection().createStatement().executeUpdate("DELETE FROM courses WHERE id=" + id);
                JOptionPane.showMessageDialog(this, "Course deleted!");
                loadCourses(); loadHomeStats();
            } 
                catch (java.sql.SQLException e) { e.printStackTrace(); }
            }
    
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnRefreshCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCoursesActionPerformed
// TODO add your handling code here:
    loadCourses();
    }//GEN-LAST:event_btnRefreshCoursesActionPerformed

    private void btnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCourseActionPerformed
// TODO add your handling code here:
        int row = tblCourses.getSelectedRow();
        if (row == -1) { JOptionPane.showMessageDialog(this, "Please select a course first!"); return; }
        int id = (int) tblCourses.getValueAt(row, 0);
        JTextField fName = new JTextField((String) tblCourses.getValueAt(row, 1));
        JTextField fInst = new JTextField((String) tblCourses.getValueAt(row, 2));
        JTextField fDur  = new JTextField((String) tblCourses.getValueAt(row, 3));
        Object[] fields = {"Course Name:", fName, "Instructor:", fInst, "Duration:", fDur};
        int result = JOptionPane.showConfirmDialog(this, fields, "Edit Course", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            try {
                java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                    "UPDATE courses SET name=?, instructor=?, duration=? WHERE id=?"
                );
                stmt.setString(1, fName.getText()); stmt.setString(2, fInst.getText());
                stmt.setString(3, fDur.getText()); stmt.setInt(4, id);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Course updated!");
                loadCourses();
            } 
            catch (java.sql.SQLException e) { e.printStackTrace(); 
            
            } 
        }
    
    }//GEN-LAST:event_btnEditCourseActionPerformed

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountActionPerformed
// TODO add your handling code here:
        try {
        java.sql.ResultSet rs = db.DBConnection.getConnection()
            .createStatement().executeQuery("SELECT COUNT(*) FROM students");
        if (rs.next()) txtResult.setText("Total Students: " + rs.getInt(1));
    } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnCountActionPerformed

    private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxActionPerformed
// TODO add your handling code here:
            try {
                java.sql.ResultSet rs = db.DBConnection.getConnection()
                    .createStatement().executeQuery("SELECT MAX(id) FROM students");
                if (rs.next()) txtResult.setText("Max Student ID: " + rs.getInt(1));
            } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnMaxActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
// TODO add your handling code here:
            try {
                java.sql.ResultSet rs = db.DBConnection.getConnection()
                    .createStatement().executeQuery("SELECT MIN(id) FROM students");
                if (rs.next()) txtResult.setText("Min Student ID: " + rs.getInt(1));
            } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopularActionPerformed
    // TODO add your handling code here:
        try {
            java.sql.ResultSet rs = db.DBConnection.getConnection().createStatement().executeQuery(
                "SELECT c.name, COUNT(*) as cnt FROM enrollments e " +
                "JOIN courses c ON e.course_id=c.id " +
                "GROUP BY e.course_id ORDER BY cnt DESC LIMIT 1"
            );
            if (rs.next())
                txtResult.setText("Most Popular: " + rs.getString("name") + " (" + rs.getInt("cnt") + " students)");
        } catch (java.sql.SQLException e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnPopularActionPerformed

    private void btnAdminLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLogoutActionPerformed
    // TODO add your handling code here:
                int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    new LoginForm().setVisible(true);
                    this.dispose();
    }
    }//GEN-LAST:event_btnAdminLogoutActionPerformed

    private void btnRefreshEnrollmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshEnrollmentsActionPerformed
// TODO add your handling code here:
    loadEnrollments();
    }//GEN-LAST:event_btnRefreshEnrollmentsActionPerformed

    private void btnDeleteEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEnrollmentActionPerformed
// TODO add your handling code here:
        int row = tblEnrollments.getSelectedRow();
        if (row == -1) { JOptionPane.showMessageDialog(this, "Please select an enrollment first!"); return; }
        int id = (int) tblEnrollments.getValueAt(row, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Delete this enrollment?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                java.sql.PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(
                    "DELETE FROM enrollments WHERE id=?"
                );
                stmt.setInt(1, id); stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Enrollment deleted!");
                loadEnrollments(); loadHomeStats();
            } 
            catch (java.sql.SQLException e) { e.printStackTrace(); 
            
            }
        }
    
    }//GEN-LAST:event_btnDeleteEnrollmentActionPerformed

    private void txtAdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminPasswordActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
    String user = txtAdminUsername.getText().trim();
    String pass = new String(txtAdminPassword.getPassword()).trim();

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter username and password");
        return;
    }

    try {
        String sql = "INSERT INTO admins (username, password) VALUES (?,?)";
        PreparedStatement stmt = db.DBConnection.getConnection().prepareStatement(sql);
        stmt.setString(1, user);
        stmt.setString(2, pass); // يفضل طبعاً استخدام التشفير hashMD5(pass)
        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "New Admin added successfully!");
        txtAdminUsername.setText("");
        txtAdminPassword.setText("");
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        int row = tblStudents.getSelectedRow();
        if (row == -1) { JOptionPane.showMessageDialog(this, "Please select a student first!"); return; }
        int id = (int) tblStudents.getValueAt(row, 0);
        String name = (String) tblStudents.getValueAt(row, 1);
        int confirm = JOptionPane.showConfirmDialog(this, "Delete " + name + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                db.DBConnection.getConnection().createStatement().executeUpdate("DELETE FROM students WHERE id=" + id);
                JOptionPane.showMessageDialog(this, "Student deleted!");
                loadStudents(); loadHomeStats();
            }
            catch (java.sql.SQLException e) { e.printStackTrace(); 
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_dashboard().setVisible(true));
        
}
    private String hashMD5(String input) {
    try {
        java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
        byte[] hash = md.digest(input.getBytes("UTF-8"));
        StringBuilder sb = new StringBuilder();
        for (byte b : hash) sb.append(String.format("%02x", b));
        return sb.toString();
    } catch (Exception e) { return input; }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAdminLogout;
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnDeleteEnrollment;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnEditCourse;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnMax;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnPopular;
    private javax.swing.JButton btnRefreshCourses;
    private javax.swing.JButton btnRefreshEnrollments;
    private javax.swing.JButton btnRefreshStudents;
    private javax.swing.JButton btnSearchCourse;
    private javax.swing.JButton btnSearchEnrollment;
    private javax.swing.JButton btnSearchStudent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCourseCount;
    private javax.swing.JLabel lblEnrollCount;
    private javax.swing.JLabel lblStudentCount;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTable tblEnrollments;
    private javax.swing.JTable tblStudents;
    private javax.swing.JPasswordField txtAdminPassword;
    private javax.swing.JTextField txtAdminUsername;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JTextField txtSearchCourse;
    private javax.swing.JTextField txtSearchEnrollment;
    private javax.swing.JTextField txtSearchStudent;
    // End of variables declaration//GEN-END:variables

}